// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOl4_82WeNt5kIohqBrkDL4l5q5vWJc4g',
    appId: '1:876278152498:web:61385dde0ee054eff92b2b',
    messagingSenderId: '876278152498',
    projectId: 'cut-go-b3b8e',
    authDomain: 'cut-go-b3b8e.firebaseapp.com',
    storageBucket: 'cut-go-b3b8e.firebasestorage.app',
    measurementId: 'G-7CT32W24FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqQlp77a6yK83Qp6jHaM7QP-duXi5SQ0',
    appId: '1:876278152498:android:f83c800f6d7a9eb4f92b2b',
    messagingSenderId: '876278152498',
    projectId: 'cut-go-b3b8e',
    storageBucket: 'cut-go-b3b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7zonmqbUIHg-XqCuuA9cQoX82I7IzJ1A',
    appId: '1:876278152498:ios:89bf9fc8e326640ff92b2b',
    messagingSenderId: '876278152498',
    projectId: 'cut-go-b3b8e',
    storageBucket: 'cut-go-b3b8e.firebasestorage.app',
    iosBundleId: 'com.example.computacionMovilProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7zonmqbUIHg-XqCuuA9cQoX82I7IzJ1A',
    appId: '1:876278152498:ios:89bf9fc8e326640ff92b2b',
    messagingSenderId: '876278152498',
    projectId: 'cut-go-b3b8e',
    storageBucket: 'cut-go-b3b8e.firebasestorage.app',
    iosBundleId: 'com.example.computacionMovilProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOl4_82WeNt5kIohqBrkDL4l5q5vWJc4g',
    appId: '1:876278152498:web:a9f05f98e7de169cf92b2b',
    messagingSenderId: '876278152498',
    projectId: 'cut-go-b3b8e',
    authDomain: 'cut-go-b3b8e.firebaseapp.com',
    storageBucket: 'cut-go-b3b8e.firebasestorage.app',
    measurementId: 'G-DHGBWT3NRM',
  );
}
